/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiKey {
  'id' : string,
  'lastUsedAt' : [] | [bigint],
  'active' : boolean,
  'ownerId' : string,
  'name' : string,
  'createdAt' : bigint,
  'totalCyclesUsed' : bigint,
  'callCount' : bigint,
}
export interface ApiKeyStats {
  'lastUsedAt' : [] | [bigint],
  'active' : boolean,
  'totalCyclesUsed' : bigint,
  'callCount' : bigint,
  'keyId' : string,
}
export interface AuditEvent {
  'id' : string,
  'userId' : string,
  'timestamp' : bigint,
  'details' : string,
  'keyId' : string,
  'eventType' : string,
}
export interface CapabilityCount { 'name' : string, 'count' : bigint }
export interface CapabilityInfo {
  'constraints' : Array<string>,
  'exampleOutput' : string,
  'name' : string,
  'exampleInput' : string,
  'description' : string,
  'inputs' : Array<CapabilityInput>,
  'category' : string,
  'outputs' : Array<CapabilityOutput>,
}
export interface CapabilityInput {
  'key' : string,
  'inputType' : string,
  'description' : string,
  'required' : boolean,
}
export interface CapabilityOutput {
  'key' : string,
  'description' : string,
  'outputType' : string,
}
export interface CapabilityTestStatus {
  'status' : string,
  'totalTests' : bigint,
  'lastRunAt' : [] | [Timestamp],
  'category' : string,
  'capabilityName' : string,
  'failed' : bigint,
  'passed' : bigint,
}
export interface DailyCount { 'date' : string, 'count' : bigint }
export interface ExecError { 'code' : string, 'message' : string }
export interface ExecutionLog {
  'output' : [] | [string],
  'apiKeyId' : [] | [string],
  'errorMessage' : [] | [string],
  'user' : UserId,
  'errorCode' : [] | [string],
  'executionId' : string,
  'latencyMs' : bigint,
  'cyclesUsed' : [] | [bigint],
  'timestamp' : Timestamp,
  'success' : boolean,
  'input' : string,
  'capability' : string,
}
export interface ExecutionResult {
  'output' : [] | [string],
  'error' : [] | [ExecError],
  'executionId' : string,
  'latencyMs' : bigint,
  'cyclesUsed' : [] | [bigint],
  'success' : boolean,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface LogFilter {
  'successOnly' : [] | [boolean],
  'user' : [] | [string],
  'offset' : [] | [bigint],
  'limit' : [] | [bigint],
  'failureOnly' : [] | [boolean],
  'capability' : [] | [string],
}
export type TestCategory = { 'MissingRequiredField' : null } |
  { 'OutputSchema' : null } |
  { 'Determinism' : null } |
  { 'EdgeCase' : null } |
  { 'RequiredFieldsOnly' : null } |
  { 'ErrorHandling' : null } |
  { 'InvalidType' : null } |
  { 'OptionalFieldIndividual' : null } |
  { 'OptionalFieldCombination' : null };
export interface TestResult {
  'inputJson' : string,
  'failureReason' : [] | [string],
  'description' : string,
  'actualErrorCode' : [] | [string],
  'latencyMs' : bigint,
  'category' : TestCategory,
  'actualSuccess' : boolean,
  'actualOutput' : [] | [string],
  'testId' : string,
  'capabilityName' : string,
  'passed' : boolean,
}
export interface TestRunMetadata {
  'completedAt' : Timestamp,
  'startedAt' : Timestamp,
  'totalTests' : bigint,
  'capabilityName' : [] | [string],
  'failed' : bigint,
  'passed' : bigint,
  'runId' : string,
}
export interface TestRunResult {
  'completedAt' : Timestamp,
  'startedAt' : Timestamp,
  'totalTests' : bigint,
  'results' : Array<TestResult>,
  'capabilityName' : [] | [string],
  'failed' : bigint,
  'passed' : bigint,
  'runId' : string,
}
export type Timestamp = bigint;
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface UsageSummary {
  'totalCalls' : bigint,
  'callsThisMonth' : bigint,
  'perUser' : Array<UserCount>,
  'dailyCounts' : Array<DailyCount>,
  'perCapability' : Array<CapabilityCount>,
}
export interface UserCount { 'count' : bigint, 'user' : UserId }
export type UserId = string;
export interface _SERVICE {
  'describe_capability' : ActorMethod<[string], [] | [CapabilityInfo]>,
  'execute_capability' : ActorMethod<
    [string, string, [] | [string]],
    ExecutionResult
  >,
  'generate_api_key' : ActorMethod<
    [string],
    { 'ok' : ApiKey } |
      { 'err' : string }
  >,
  'get_admin_status' : ActorMethod<[], boolean>,
  'get_api_key_stats' : ActorMethod<
    [string],
    { 'ok' : ApiKeyStats } |
      { 'err' : string }
  >,
  'get_audit_log' : ActorMethod<[bigint, bigint], Array<AuditEvent>>,
  'get_capability_test_statuses' : ActorMethod<[], Array<CapabilityTestStatus>>,
  'get_execution_logs' : ActorMethod<[LogFilter], Array<ExecutionLog>>,
  'get_integration_info' : ActorMethod<
    [],
    {
      'candid_example' : string,
      'key_location' : string,
      'http_method' : string,
      'key_param_name' : string,
      'rate_limit_info' : string,
    }
  >,
  'get_test_history' : ActorMethod<[], Array<TestRunMetadata>>,
  'get_test_results' : ActorMethod<[string], [] | [TestRunResult]>,
  'get_usage_summary' : ActorMethod<[], UsageSummary>,
  'list_capabilities' : ActorMethod<[[] | [string]], Array<CapabilityInfo>>,
  'list_my_api_keys' : ActorMethod<[], Array<ApiKey>>,
  'revoke_api_key' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'run_all_tests' : ActorMethod<[], TestRunResult>,
  'run_capability_tests' : ActorMethod<[string], TestRunResult>,
  'transform_http_response' : ActorMethod<[TransformArgs], HttpRequestResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];