/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CapabilityInput = IDL.Record({
  'key' : IDL.Text,
  'inputType' : IDL.Text,
  'description' : IDL.Text,
  'required' : IDL.Bool,
});
export const CapabilityOutput = IDL.Record({
  'key' : IDL.Text,
  'description' : IDL.Text,
  'outputType' : IDL.Text,
});
export const CapabilityInfo = IDL.Record({
  'constraints' : IDL.Vec(IDL.Text),
  'exampleOutput' : IDL.Text,
  'name' : IDL.Text,
  'exampleInput' : IDL.Text,
  'description' : IDL.Text,
  'inputs' : IDL.Vec(CapabilityInput),
  'category' : IDL.Text,
  'outputs' : IDL.Vec(CapabilityOutput),
});
export const ExecError = IDL.Record({
  'code' : IDL.Text,
  'message' : IDL.Text,
});
export const ExecutionResult = IDL.Record({
  'output' : IDL.Opt(IDL.Text),
  'error' : IDL.Opt(ExecError),
  'executionId' : IDL.Text,
  'latencyMs' : IDL.Nat,
  'cyclesUsed' : IDL.Opt(IDL.Nat),
  'success' : IDL.Bool,
});
export const ApiKey = IDL.Record({
  'id' : IDL.Text,
  'lastUsedAt' : IDL.Opt(IDL.Int),
  'active' : IDL.Bool,
  'ownerId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalCyclesUsed' : IDL.Nat,
  'callCount' : IDL.Nat,
});
export const ApiKeyStats = IDL.Record({
  'lastUsedAt' : IDL.Opt(IDL.Int),
  'active' : IDL.Bool,
  'totalCyclesUsed' : IDL.Nat,
  'callCount' : IDL.Nat,
  'keyId' : IDL.Text,
});
export const AuditEvent = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'keyId' : IDL.Text,
  'eventType' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const CapabilityTestStatus = IDL.Record({
  'status' : IDL.Text,
  'totalTests' : IDL.Nat,
  'lastRunAt' : IDL.Opt(Timestamp),
  'category' : IDL.Text,
  'capabilityName' : IDL.Text,
  'failed' : IDL.Nat,
  'passed' : IDL.Nat,
});
export const LogFilter = IDL.Record({
  'successOnly' : IDL.Opt(IDL.Bool),
  'user' : IDL.Opt(IDL.Text),
  'offset' : IDL.Opt(IDL.Nat),
  'limit' : IDL.Opt(IDL.Nat),
  'failureOnly' : IDL.Opt(IDL.Bool),
  'capability' : IDL.Opt(IDL.Text),
});
export const UserId = IDL.Text;
export const ExecutionLog = IDL.Record({
  'output' : IDL.Opt(IDL.Text),
  'apiKeyId' : IDL.Opt(IDL.Text),
  'errorMessage' : IDL.Opt(IDL.Text),
  'user' : UserId,
  'errorCode' : IDL.Opt(IDL.Text),
  'executionId' : IDL.Text,
  'latencyMs' : IDL.Nat,
  'cyclesUsed' : IDL.Opt(IDL.Nat),
  'timestamp' : Timestamp,
  'success' : IDL.Bool,
  'input' : IDL.Text,
  'capability' : IDL.Text,
});
export const TestRunMetadata = IDL.Record({
  'completedAt' : Timestamp,
  'startedAt' : Timestamp,
  'totalTests' : IDL.Nat,
  'capabilityName' : IDL.Opt(IDL.Text),
  'failed' : IDL.Nat,
  'passed' : IDL.Nat,
  'runId' : IDL.Text,
});
export const TestCategory = IDL.Variant({
  'MissingRequiredField' : IDL.Null,
  'OutputSchema' : IDL.Null,
  'Determinism' : IDL.Null,
  'EdgeCase' : IDL.Null,
  'RequiredFieldsOnly' : IDL.Null,
  'ErrorHandling' : IDL.Null,
  'InvalidType' : IDL.Null,
  'OptionalFieldIndividual' : IDL.Null,
  'OptionalFieldCombination' : IDL.Null,
});
export const TestResult = IDL.Record({
  'inputJson' : IDL.Text,
  'failureReason' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'actualErrorCode' : IDL.Opt(IDL.Text),
  'latencyMs' : IDL.Nat,
  'category' : TestCategory,
  'actualSuccess' : IDL.Bool,
  'actualOutput' : IDL.Opt(IDL.Text),
  'testId' : IDL.Text,
  'capabilityName' : IDL.Text,
  'passed' : IDL.Bool,
});
export const TestRunResult = IDL.Record({
  'completedAt' : Timestamp,
  'startedAt' : Timestamp,
  'totalTests' : IDL.Nat,
  'results' : IDL.Vec(TestResult),
  'capabilityName' : IDL.Opt(IDL.Text),
  'failed' : IDL.Nat,
  'passed' : IDL.Nat,
  'runId' : IDL.Text,
});
export const UserCount = IDL.Record({ 'count' : IDL.Nat, 'user' : UserId });
export const DailyCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const CapabilityCount = IDL.Record({
  'name' : IDL.Text,
  'count' : IDL.Nat,
});
export const UsageSummary = IDL.Record({
  'totalCalls' : IDL.Nat,
  'callsThisMonth' : IDL.Nat,
  'perUser' : IDL.Vec(UserCount),
  'dailyCounts' : IDL.Vec(DailyCount),
  'perCapability' : IDL.Vec(CapabilityCount),
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});

export const idlService = IDL.Service({
  'describe_capability' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CapabilityInfo)],
      ['query'],
    ),
  'execute_capability' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [ExecutionResult],
      [],
    ),
  'generate_api_key' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ApiKey, 'err' : IDL.Text })],
      [],
    ),
  'get_admin_status' : IDL.Func([], [IDL.Bool], []),
  'get_api_key_stats' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ApiKeyStats, 'err' : IDL.Text })],
      ['query'],
    ),
  'get_audit_log' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditEvent)],
      ['query'],
    ),
  'get_capability_test_statuses' : IDL.Func(
      [],
      [IDL.Vec(CapabilityTestStatus)],
      ['query'],
    ),
  'get_execution_logs' : IDL.Func(
      [LogFilter],
      [IDL.Vec(ExecutionLog)],
      ['query'],
    ),
  'get_integration_info' : IDL.Func(
      [],
      [
        IDL.Record({
          'candid_example' : IDL.Text,
          'key_location' : IDL.Text,
          'http_method' : IDL.Text,
          'key_param_name' : IDL.Text,
          'rate_limit_info' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'get_test_history' : IDL.Func([], [IDL.Vec(TestRunMetadata)], ['query']),
  'get_test_results' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TestRunResult)],
      ['query'],
    ),
  'get_usage_summary' : IDL.Func([], [UsageSummary], ['query']),
  'list_capabilities' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(CapabilityInfo)],
      ['query'],
    ),
  'list_my_api_keys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
  'revoke_api_key' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'run_all_tests' : IDL.Func([], [TestRunResult], []),
  'run_capability_tests' : IDL.Func([IDL.Text], [TestRunResult], []),
  'transform_http_response' : IDL.Func(
      [TransformArgs],
      [HttpRequestResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CapabilityInput = IDL.Record({
    'key' : IDL.Text,
    'inputType' : IDL.Text,
    'description' : IDL.Text,
    'required' : IDL.Bool,
  });
  const CapabilityOutput = IDL.Record({
    'key' : IDL.Text,
    'description' : IDL.Text,
    'outputType' : IDL.Text,
  });
  const CapabilityInfo = IDL.Record({
    'constraints' : IDL.Vec(IDL.Text),
    'exampleOutput' : IDL.Text,
    'name' : IDL.Text,
    'exampleInput' : IDL.Text,
    'description' : IDL.Text,
    'inputs' : IDL.Vec(CapabilityInput),
    'category' : IDL.Text,
    'outputs' : IDL.Vec(CapabilityOutput),
  });
  const ExecError = IDL.Record({ 'code' : IDL.Text, 'message' : IDL.Text });
  const ExecutionResult = IDL.Record({
    'output' : IDL.Opt(IDL.Text),
    'error' : IDL.Opt(ExecError),
    'executionId' : IDL.Text,
    'latencyMs' : IDL.Nat,
    'cyclesUsed' : IDL.Opt(IDL.Nat),
    'success' : IDL.Bool,
  });
  const ApiKey = IDL.Record({
    'id' : IDL.Text,
    'lastUsedAt' : IDL.Opt(IDL.Int),
    'active' : IDL.Bool,
    'ownerId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalCyclesUsed' : IDL.Nat,
    'callCount' : IDL.Nat,
  });
  const ApiKeyStats = IDL.Record({
    'lastUsedAt' : IDL.Opt(IDL.Int),
    'active' : IDL.Bool,
    'totalCyclesUsed' : IDL.Nat,
    'callCount' : IDL.Nat,
    'keyId' : IDL.Text,
  });
  const AuditEvent = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'keyId' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const CapabilityTestStatus = IDL.Record({
    'status' : IDL.Text,
    'totalTests' : IDL.Nat,
    'lastRunAt' : IDL.Opt(Timestamp),
    'category' : IDL.Text,
    'capabilityName' : IDL.Text,
    'failed' : IDL.Nat,
    'passed' : IDL.Nat,
  });
  const LogFilter = IDL.Record({
    'successOnly' : IDL.Opt(IDL.Bool),
    'user' : IDL.Opt(IDL.Text),
    'offset' : IDL.Opt(IDL.Nat),
    'limit' : IDL.Opt(IDL.Nat),
    'failureOnly' : IDL.Opt(IDL.Bool),
    'capability' : IDL.Opt(IDL.Text),
  });
  const UserId = IDL.Text;
  const ExecutionLog = IDL.Record({
    'output' : IDL.Opt(IDL.Text),
    'apiKeyId' : IDL.Opt(IDL.Text),
    'errorMessage' : IDL.Opt(IDL.Text),
    'user' : UserId,
    'errorCode' : IDL.Opt(IDL.Text),
    'executionId' : IDL.Text,
    'latencyMs' : IDL.Nat,
    'cyclesUsed' : IDL.Opt(IDL.Nat),
    'timestamp' : Timestamp,
    'success' : IDL.Bool,
    'input' : IDL.Text,
    'capability' : IDL.Text,
  });
  const TestRunMetadata = IDL.Record({
    'completedAt' : Timestamp,
    'startedAt' : Timestamp,
    'totalTests' : IDL.Nat,
    'capabilityName' : IDL.Opt(IDL.Text),
    'failed' : IDL.Nat,
    'passed' : IDL.Nat,
    'runId' : IDL.Text,
  });
  const TestCategory = IDL.Variant({
    'MissingRequiredField' : IDL.Null,
    'OutputSchema' : IDL.Null,
    'Determinism' : IDL.Null,
    'EdgeCase' : IDL.Null,
    'RequiredFieldsOnly' : IDL.Null,
    'ErrorHandling' : IDL.Null,
    'InvalidType' : IDL.Null,
    'OptionalFieldIndividual' : IDL.Null,
    'OptionalFieldCombination' : IDL.Null,
  });
  const TestResult = IDL.Record({
    'inputJson' : IDL.Text,
    'failureReason' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'actualErrorCode' : IDL.Opt(IDL.Text),
    'latencyMs' : IDL.Nat,
    'category' : TestCategory,
    'actualSuccess' : IDL.Bool,
    'actualOutput' : IDL.Opt(IDL.Text),
    'testId' : IDL.Text,
    'capabilityName' : IDL.Text,
    'passed' : IDL.Bool,
  });
  const TestRunResult = IDL.Record({
    'completedAt' : Timestamp,
    'startedAt' : Timestamp,
    'totalTests' : IDL.Nat,
    'results' : IDL.Vec(TestResult),
    'capabilityName' : IDL.Opt(IDL.Text),
    'failed' : IDL.Nat,
    'passed' : IDL.Nat,
    'runId' : IDL.Text,
  });
  const UserCount = IDL.Record({ 'count' : IDL.Nat, 'user' : UserId });
  const DailyCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const CapabilityCount = IDL.Record({ 'name' : IDL.Text, 'count' : IDL.Nat });
  const UsageSummary = IDL.Record({
    'totalCalls' : IDL.Nat,
    'callsThisMonth' : IDL.Nat,
    'perUser' : IDL.Vec(UserCount),
    'dailyCounts' : IDL.Vec(DailyCount),
    'perCapability' : IDL.Vec(CapabilityCount),
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  
  return IDL.Service({
    'describe_capability' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CapabilityInfo)],
        ['query'],
      ),
    'execute_capability' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [ExecutionResult],
        [],
      ),
    'generate_api_key' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ApiKey, 'err' : IDL.Text })],
        [],
      ),
    'get_admin_status' : IDL.Func([], [IDL.Bool], []),
    'get_api_key_stats' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ApiKeyStats, 'err' : IDL.Text })],
        ['query'],
      ),
    'get_audit_log' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditEvent)],
        ['query'],
      ),
    'get_capability_test_statuses' : IDL.Func(
        [],
        [IDL.Vec(CapabilityTestStatus)],
        ['query'],
      ),
    'get_execution_logs' : IDL.Func(
        [LogFilter],
        [IDL.Vec(ExecutionLog)],
        ['query'],
      ),
    'get_integration_info' : IDL.Func(
        [],
        [
          IDL.Record({
            'candid_example' : IDL.Text,
            'key_location' : IDL.Text,
            'http_method' : IDL.Text,
            'key_param_name' : IDL.Text,
            'rate_limit_info' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'get_test_history' : IDL.Func([], [IDL.Vec(TestRunMetadata)], ['query']),
    'get_test_results' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TestRunResult)],
        ['query'],
      ),
    'get_usage_summary' : IDL.Func([], [UsageSummary], ['query']),
    'list_capabilities' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(CapabilityInfo)],
        ['query'],
      ),
    'list_my_api_keys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
    'revoke_api_key' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'run_all_tests' : IDL.Func([], [TestRunResult], []),
    'run_capability_tests' : IDL.Func([IDL.Text], [TestRunResult], []),
    'transform_http_response' : IDL.Func(
        [TransformArgs],
        [HttpRequestResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };