/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CapabilityOutput {
    key: string;
    description: string;
    outputType: string;
}
export interface ExecutionResult {
    output?: string;
    error?: ExecError;
    executionId: string;
    latencyMs: bigint;
    cyclesUsed?: bigint;
    success: boolean;
}
export type Timestamp = bigint;
export interface TestRunResult {
    completedAt: Timestamp;
    startedAt: Timestamp;
    totalTests: bigint;
    results: Array<TestResult>;
    capabilityName?: string;
    failed: bigint;
    passed: bigint;
    runId: string;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface UsageSummary {
    totalCalls: bigint;
    callsThisMonth: bigint;
    perUser: Array<UserCount>;
    dailyCounts: Array<DailyCount>;
    perCapability: Array<CapabilityCount>;
}
export interface ExecutionLog {
    output?: string;
    apiKeyId?: string;
    errorMessage?: string;
    user: UserId;
    errorCode?: string;
    executionId: string;
    latencyMs: bigint;
    cyclesUsed?: bigint;
    timestamp: Timestamp;
    success: boolean;
    input: string;
    capability: string;
}
export interface TestRunMetadata {
    completedAt: Timestamp;
    startedAt: Timestamp;
    totalTests: bigint;
    capabilityName?: string;
    failed: bigint;
    passed: bigint;
    runId: string;
}
export interface CapabilityTestStatus {
    status: string;
    totalTests: bigint;
    lastRunAt?: Timestamp;
    category: string;
    capabilityName: string;
    failed: bigint;
    passed: bigint;
}
export interface CapabilityCount {
    name: string;
    count: bigint;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface TestResult {
    inputJson: string;
    failureReason?: string;
    description: string;
    actualErrorCode?: string;
    latencyMs: bigint;
    category: TestCategory;
    actualSuccess: boolean;
    actualOutput?: string;
    testId: string;
    capabilityName: string;
    passed: boolean;
}
export type UserId = string;
export interface ExecError {
    code: string;
    message: string;
}
export interface UserCount {
    count: bigint;
    user: UserId;
}
export interface DailyCount {
    date: string;
    count: bigint;
}
export interface CapabilityInput {
    key: string;
    inputType: string;
    description: string;
    required: boolean;
}
export interface AuditEvent {
    id: string;
    userId: string;
    timestamp: bigint;
    details: string;
    keyId: string;
    eventType: string;
}
export interface ApiKeyStats {
    lastUsedAt?: bigint;
    active: boolean;
    totalCyclesUsed: bigint;
    callCount: bigint;
    keyId: string;
}
export interface ApiKey {
    id: string;
    lastUsedAt?: bigint;
    active: boolean;
    ownerId: string;
    name: string;
    createdAt: bigint;
    totalCyclesUsed: bigint;
    callCount: bigint;
}
export interface LogFilter {
    successOnly?: boolean;
    user?: string;
    offset?: bigint;
    limit?: bigint;
    failureOnly?: boolean;
    capability?: string;
}
export interface CapabilityInfo {
    constraints: Array<string>;
    exampleOutput: string;
    name: string;
    exampleInput: string;
    description: string;
    inputs: Array<CapabilityInput>;
    category: string;
    outputs: Array<CapabilityOutput>;
}
export interface TransformArgs {
    context: Uint8Array;
    response: HttpRequestResult;
}
export enum TestCategory {
    MissingRequiredField = "MissingRequiredField",
    OutputSchema = "OutputSchema",
    Determinism = "Determinism",
    EdgeCase = "EdgeCase",
    RequiredFieldsOnly = "RequiredFieldsOnly",
    ErrorHandling = "ErrorHandling",
    InvalidType = "InvalidType",
    OptionalFieldIndividual = "OptionalFieldIndividual",
    OptionalFieldCombination = "OptionalFieldCombination"
}
export interface backendInterface {
    describe_capability(name: string): Promise<CapabilityInfo | null>;
    execute_capability(capabilityName: string, inputJson: string, apiKey: string | null): Promise<ExecutionResult>;
    generate_api_key(name: string): Promise<{
        __kind__: "ok";
        ok: ApiKey;
    } | {
        __kind__: "err";
        err: string;
    }>;
    get_admin_status(): Promise<boolean>;
    get_api_key_stats(keyId: string): Promise<{
        __kind__: "ok";
        ok: ApiKeyStats;
    } | {
        __kind__: "err";
        err: string;
    }>;
    get_audit_log(limit: bigint, offset: bigint): Promise<Array<AuditEvent>>;
    get_capability_test_statuses(): Promise<Array<CapabilityTestStatus>>;
    get_execution_logs(filter: LogFilter): Promise<Array<ExecutionLog>>;
    get_integration_info(): Promise<{
        candid_example: string;
        key_location: string;
        http_method: string;
        key_param_name: string;
        rate_limit_info: string;
    }>;
    get_test_history(): Promise<Array<TestRunMetadata>>;
    get_test_results(runId: string): Promise<TestRunResult | null>;
    get_usage_summary(): Promise<UsageSummary>;
    list_capabilities(categoryFilter: string | null): Promise<Array<CapabilityInfo>>;
    list_my_api_keys(): Promise<Array<ApiKey>>;
    revoke_api_key(keyId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    run_all_tests(): Promise<TestRunResult>;
    run_capability_tests(capabilityName: string): Promise<TestRunResult>;
    transform_http_response(raw: TransformArgs): Promise<HttpRequestResult>;
}
import type { ApiKey as _ApiKey, ApiKeyStats as _ApiKeyStats, CapabilityInfo as _CapabilityInfo, CapabilityTestStatus as _CapabilityTestStatus, ExecError as _ExecError, ExecutionLog as _ExecutionLog, ExecutionResult as _ExecutionResult, LogFilter as _LogFilter, TestCategory as _TestCategory, TestResult as _TestResult, TestRunMetadata as _TestRunMetadata, TestRunResult as _TestRunResult, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async describe_capability(arg0: string): Promise<CapabilityInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.describe_capability(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.describe_capability(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute_capability(arg0: string, arg1: string, arg2: string | null): Promise<ExecutionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.execute_capability(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ExecutionResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute_capability(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ExecutionResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async generate_api_key(arg0: string): Promise<{
        __kind__: "ok";
        ok: ApiKey;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.generate_api_key(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generate_api_key(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_admin_status(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.get_admin_status();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_admin_status();
            return result;
        }
    }
    async get_api_key_stats(arg0: string): Promise<{
        __kind__: "ok";
        ok: ApiKeyStats;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.get_api_key_stats(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_api_key_stats(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_audit_log(arg0: bigint, arg1: bigint): Promise<Array<AuditEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_audit_log(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_audit_log(arg0, arg1);
            return result;
        }
    }
    async get_capability_test_statuses(): Promise<Array<CapabilityTestStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_capability_test_statuses();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_capability_test_statuses();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_execution_logs(arg0: LogFilter): Promise<Array<ExecutionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_execution_logs(to_candid_LogFilter_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_execution_logs(to_candid_LogFilter_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_integration_info(): Promise<{
        candid_example: string;
        key_location: string;
        http_method: string;
        key_param_name: string;
        rate_limit_info: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.get_integration_info();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_integration_info();
            return result;
        }
    }
    async get_test_history(): Promise<Array<TestRunMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_test_history();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_test_history();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_test_results(arg0: string): Promise<TestRunResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_test_results(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_test_results(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_usage_summary(): Promise<UsageSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.get_usage_summary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_usage_summary();
            return result;
        }
    }
    async list_capabilities(arg0: string | null): Promise<Array<CapabilityInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.list_capabilities(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.list_capabilities(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async list_my_api_keys(): Promise<Array<ApiKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.list_my_api_keys();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.list_my_api_keys();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async revoke_api_key(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.revoke_api_key(arg0);
                return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revoke_api_key(arg0);
            return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async run_all_tests(): Promise<TestRunResult> {
        if (this.processError) {
            try {
                const result = await this.actor.run_all_tests();
                return from_candid_TestRunResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.run_all_tests();
            return from_candid_TestRunResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async run_capability_tests(arg0: string): Promise<TestRunResult> {
        if (this.processError) {
            try {
                const result = await this.actor.run_capability_tests(arg0);
                return from_candid_TestRunResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.run_capability_tests(arg0);
            return from_candid_TestRunResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform_http_response(arg0: TransformArgs): Promise<HttpRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transform_http_response(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform_http_response(arg0);
            return result;
        }
    }
}
function from_candid_ApiKeyStats_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiKeyStats): ApiKeyStats {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ApiKey_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiKey): ApiKey {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CapabilityTestStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CapabilityTestStatus): CapabilityTestStatus {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ExecutionLog_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionLog): ExecutionLog {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ExecutionResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionResult): ExecutionResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TestCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestCategory): TestCategory {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_TestResult_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestResult): TestResult {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_TestRunMetadata_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestRunMetadata): TestRunMetadata {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TestRunResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestRunResult): TestRunResult {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CapabilityInfo]): CapabilityInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestRunResult]): TestRunResult | null {
    return value.length === 0 ? null : from_candid_TestRunResult_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExecError]): ExecError | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lastUsedAt: [] | [bigint];
    active: boolean;
    ownerId: string;
    name: string;
    createdAt: bigint;
    totalCyclesUsed: bigint;
    callCount: bigint;
}): {
    id: string;
    lastUsedAt?: bigint;
    active: boolean;
    ownerId: string;
    name: string;
    createdAt: bigint;
    totalCyclesUsed: bigint;
    callCount: bigint;
} {
    return {
        id: value.id,
        lastUsedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lastUsedAt)),
        active: value.active,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        totalCyclesUsed: value.totalCyclesUsed,
        callCount: value.callCount
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastUsedAt: [] | [bigint];
    active: boolean;
    totalCyclesUsed: bigint;
    callCount: bigint;
    keyId: string;
}): {
    lastUsedAt?: bigint;
    active: boolean;
    totalCyclesUsed: bigint;
    callCount: bigint;
    keyId: string;
} {
    return {
        lastUsedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lastUsedAt)),
        active: value.active,
        totalCyclesUsed: value.totalCyclesUsed,
        callCount: value.callCount,
        keyId: value.keyId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    totalTests: bigint;
    lastRunAt: [] | [_Timestamp];
    category: string;
    capabilityName: string;
    failed: bigint;
    passed: bigint;
}): {
    status: string;
    totalTests: bigint;
    lastRunAt?: Timestamp;
    category: string;
    capabilityName: string;
    failed: bigint;
    passed: bigint;
} {
    return {
        status: value.status,
        totalTests: value.totalTests,
        lastRunAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.lastRunAt)),
        category: value.category,
        capabilityName: value.capabilityName,
        failed: value.failed,
        passed: value.passed
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    output: [] | [string];
    apiKeyId: [] | [string];
    errorMessage: [] | [string];
    user: _UserId;
    errorCode: [] | [string];
    executionId: string;
    latencyMs: bigint;
    cyclesUsed: [] | [bigint];
    timestamp: _Timestamp;
    success: boolean;
    input: string;
    capability: string;
}): {
    output?: string;
    apiKeyId?: string;
    errorMessage?: string;
    user: UserId;
    errorCode?: string;
    executionId: string;
    latencyMs: bigint;
    cyclesUsed?: bigint;
    timestamp: Timestamp;
    success: boolean;
    input: string;
    capability: string;
} {
    return {
        output: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.output)),
        apiKeyId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.apiKeyId)),
        errorMessage: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.errorMessage)),
        user: value.user,
        errorCode: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.errorCode)),
        executionId: value.executionId,
        latencyMs: value.latencyMs,
        cyclesUsed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cyclesUsed)),
        timestamp: value.timestamp,
        success: value.success,
        input: value.input,
        capability: value.capability
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Timestamp;
    startedAt: _Timestamp;
    totalTests: bigint;
    capabilityName: [] | [string];
    failed: bigint;
    passed: bigint;
    runId: string;
}): {
    completedAt: Timestamp;
    startedAt: Timestamp;
    totalTests: bigint;
    capabilityName?: string;
    failed: bigint;
    passed: bigint;
    runId: string;
} {
    return {
        completedAt: value.completedAt,
        startedAt: value.startedAt,
        totalTests: value.totalTests,
        capabilityName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.capabilityName)),
        failed: value.failed,
        passed: value.passed,
        runId: value.runId
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Timestamp;
    startedAt: _Timestamp;
    totalTests: bigint;
    results: Array<_TestResult>;
    capabilityName: [] | [string];
    failed: bigint;
    passed: bigint;
    runId: string;
}): {
    completedAt: Timestamp;
    startedAt: Timestamp;
    totalTests: bigint;
    results: Array<TestResult>;
    capabilityName?: string;
    failed: bigint;
    passed: bigint;
    runId: string;
} {
    return {
        completedAt: value.completedAt,
        startedAt: value.startedAt,
        totalTests: value.totalTests,
        results: from_candid_vec_n30(_uploadFile, _downloadFile, value.results),
        capabilityName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.capabilityName)),
        failed: value.failed,
        passed: value.passed,
        runId: value.runId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inputJson: string;
    failureReason: [] | [string];
    description: string;
    actualErrorCode: [] | [string];
    latencyMs: bigint;
    category: _TestCategory;
    actualSuccess: boolean;
    actualOutput: [] | [string];
    testId: string;
    capabilityName: string;
    passed: boolean;
}): {
    inputJson: string;
    failureReason?: string;
    description: string;
    actualErrorCode?: string;
    latencyMs: bigint;
    category: TestCategory;
    actualSuccess: boolean;
    actualOutput?: string;
    testId: string;
    capabilityName: string;
    passed: boolean;
} {
    return {
        inputJson: value.inputJson,
        failureReason: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.failureReason)),
        description: value.description,
        actualErrorCode: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.actualErrorCode)),
        latencyMs: value.latencyMs,
        category: from_candid_TestCategory_n33(_uploadFile, _downloadFile, value.category),
        actualSuccess: value.actualSuccess,
        actualOutput: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.actualOutput)),
        testId: value.testId,
        capabilityName: value.capabilityName,
        passed: value.passed
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    output: [] | [string];
    error: [] | [_ExecError];
    executionId: string;
    latencyMs: bigint;
    cyclesUsed: [] | [bigint];
    success: boolean;
}): {
    output?: string;
    error?: ExecError;
    executionId: string;
    latencyMs: bigint;
    cyclesUsed?: bigint;
    success: boolean;
} {
    return {
        output: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.output)),
        error: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.error)),
        executionId: value.executionId,
        latencyMs: value.latencyMs,
        cyclesUsed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cyclesUsed)),
        success: value.success
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ApiKeyStats;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ApiKeyStats;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ApiKeyStats_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MissingRequiredField: null;
} | {
    OutputSchema: null;
} | {
    Determinism: null;
} | {
    EdgeCase: null;
} | {
    RequiredFieldsOnly: null;
} | {
    ErrorHandling: null;
} | {
    InvalidType: null;
} | {
    OptionalFieldIndividual: null;
} | {
    OptionalFieldCombination: null;
}): TestCategory {
    return "MissingRequiredField" in value ? TestCategory.MissingRequiredField : "OutputSchema" in value ? TestCategory.OutputSchema : "Determinism" in value ? TestCategory.Determinism : "EdgeCase" in value ? TestCategory.EdgeCase : "RequiredFieldsOnly" in value ? TestCategory.RequiredFieldsOnly : "ErrorHandling" in value ? TestCategory.ErrorHandling : "InvalidType" in value ? TestCategory.InvalidType : "OptionalFieldIndividual" in value ? TestCategory.OptionalFieldIndividual : "OptionalFieldCombination" in value ? TestCategory.OptionalFieldCombination : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ApiKey;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ApiKey;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ApiKey_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CapabilityTestStatus>): Array<CapabilityTestStatus> {
    return value.map((x)=>from_candid_CapabilityTestStatus_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExecutionLog>): Array<ExecutionLog> {
    return value.map((x)=>from_candid_ExecutionLog_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestRunMetadata>): Array<TestRunMetadata> {
    return value.map((x)=>from_candid_TestRunMetadata_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestResult>): Array<TestResult> {
    return value.map((x)=>from_candid_TestResult_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiKey>): Array<ApiKey> {
    return value.map((x)=>from_candid_ApiKey_n9(_uploadFile, _downloadFile, x));
}
function to_candid_LogFilter_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogFilter): _LogFilter {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    successOnly?: boolean;
    user?: string;
    offset?: bigint;
    limit?: bigint;
    failureOnly?: boolean;
    capability?: string;
}): {
    successOnly: [] | [boolean];
    user: [] | [string];
    offset: [] | [bigint];
    limit: [] | [bigint];
    failureOnly: [] | [boolean];
    capability: [] | [string];
} {
    return {
        successOnly: value.successOnly ? candid_some(value.successOnly) : candid_none(),
        user: value.user ? candid_some(value.user) : candid_none(),
        offset: value.offset ? candid_some(value.offset) : candid_none(),
        limit: value.limit ? candid_some(value.limit) : candid_none(),
        failureOnly: value.failureOnly ? candid_some(value.failureOnly) : candid_none(),
        capability: value.capability ? candid_some(value.capability) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
